export { LogoSVG } from './Logo'
export { InstagramSVG } from './Instagram'
export { TelegramSVG } from './Telegram'
export { VKontakteSVG } from './Vkontakte'
export { WhatsAppSVG } from './WhatsApp'
