import type { Metadata } from 'next'

import './globals.css'
import { cn, open_sans } from '@/utils'
import { Footer, Header } from '@/components'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'w-full max-w-5xl m-auto h-full min-h-screen flex flex-col justify-between items-center',
                    open_sans.className
                )}
            >
                <Header />
                <main className="flex-grow py-10">{children}</main>
                <Footer />
            </body>
        </html>
    )
}
